/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class yap implements yapConstants {
  public static SWIGTYPE_p_Term YAP_ReadBuffer(String s, SWIGTYPE_p_Term tp) {
    return new SWIGTYPE_p_Term(yapJNI.YAP_ReadBuffer(s, SWIGTYPE_p_Term.getCPtr(tp)), true);
  }

}
