/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class YAPApplTerm extends YAPTerm {
  private transient long swigCPtr;

  protected YAPApplTerm(long cPtr, boolean cMemoryOwn) {
    super(yapJNI.YAPApplTerm_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YAPApplTerm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yapJNI.delete_YAPApplTerm(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public YAPApplTerm(YAPFunctor f, YAPTerm ts) {
    this(yapJNI.new_YAPApplTerm__SWIG_0(YAPFunctor.getCPtr(f), f, YAPTerm.getCPtr(ts), ts), true);
  }

  public YAPApplTerm(YAPFunctor f) {
    this(yapJNI.new_YAPApplTerm__SWIG_1(YAPFunctor.getCPtr(f), f), true);
  }

  public YAPFunctor getFunctor() {
    return new YAPFunctor(yapJNI.YAPApplTerm_getFunctor(swigCPtr, this), true);
  }

  public YAPTerm getArg(long i) {
    return new YAPTerm(yapJNI.YAPApplTerm_getArg(swigCPtr, this, i), true);
  }

  public boolean isVar() {
    return yapJNI.YAPApplTerm_isVar(swigCPtr, this);
  }

  public boolean isAtom() {
    return yapJNI.YAPApplTerm_isAtom(swigCPtr, this);
  }

  public boolean isInteger() {
    return yapJNI.YAPApplTerm_isInteger(swigCPtr, this);
  }

  public boolean isFloat() {
    return yapJNI.YAPApplTerm_isFloat(swigCPtr, this);
  }

  public boolean isString() {
    return yapJNI.YAPApplTerm_isString(swigCPtr, this);
  }

  public boolean isCompound() {
    return yapJNI.YAPApplTerm_isCompound(swigCPtr, this);
  }

  public boolean isAppl() {
    return yapJNI.YAPApplTerm_isAppl(swigCPtr, this);
  }

  public boolean isPair() {
    return yapJNI.YAPApplTerm_isPair(swigCPtr, this);
  }

  public boolean isGround() {
    return yapJNI.YAPApplTerm_isGround(swigCPtr, this);
  }

  public boolean isList() {
    return yapJNI.YAPApplTerm_isList(swigCPtr, this);
  }

}
