/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class YAPAtomTerm extends YAPTerm {
  private transient long swigCPtr;

  protected YAPAtomTerm(long cPtr, boolean cMemoryOwn) {
    super(yapJNI.YAPAtomTerm_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YAPAtomTerm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yapJNI.delete_YAPAtomTerm(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public YAPAtomTerm(YAPAtom a) {
    this(yapJNI.new_YAPAtomTerm__SWIG_0(YAPAtom.getCPtr(a), a), true);
  }

  public YAPAtomTerm(String s) {
    this(yapJNI.new_YAPAtomTerm__SWIG_1(s), true);
  }

  public YAPAtomTerm(String s, long len) {
    this(yapJNI.new_YAPAtomTerm__SWIG_2(s, len), true);
  }

  public YAPAtomTerm(SWIGTYPE_p_wchar_t s) {
    this(yapJNI.new_YAPAtomTerm__SWIG_3(SWIGTYPE_p_wchar_t.getCPtr(s)), true);
  }

  public YAPAtomTerm(SWIGTYPE_p_wchar_t s, long len) {
    this(yapJNI.new_YAPAtomTerm__SWIG_4(SWIGTYPE_p_wchar_t.getCPtr(s), len), true);
  }

  public boolean isVar() {
    return yapJNI.YAPAtomTerm_isVar(swigCPtr, this);
  }

  public boolean isAtom() {
    return yapJNI.YAPAtomTerm_isAtom(swigCPtr, this);
  }

  public boolean isInteger() {
    return yapJNI.YAPAtomTerm_isInteger(swigCPtr, this);
  }

  public boolean isFloat() {
    return yapJNI.YAPAtomTerm_isFloat(swigCPtr, this);
  }

  public boolean isString() {
    return yapJNI.YAPAtomTerm_isString(swigCPtr, this);
  }

  public boolean isCompound() {
    return yapJNI.YAPAtomTerm_isCompound(swigCPtr, this);
  }

  public boolean isAppl() {
    return yapJNI.YAPAtomTerm_isAppl(swigCPtr, this);
  }

  public boolean isPair() {
    return yapJNI.YAPAtomTerm_isPair(swigCPtr, this);
  }

  public boolean isGround() {
    return yapJNI.YAPAtomTerm_isGround(swigCPtr, this);
  }

  public boolean isList() {
    return yapJNI.YAPAtomTerm_isList(swigCPtr, this);
  }

  public YAPAtom getAtom() {
    return new YAPAtom(yapJNI.YAPAtomTerm_getAtom(swigCPtr, this), true);
  }

  public String text() {
    return yapJNI.YAPAtomTerm_text(swigCPtr, this);
  }

}
