/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public interface yapConstants {
  public final static int YAPA_HH = yapJNI.YAPA_HH_get();
  public final static int YAPT_HH = yapJNI.YAPT_HH_get();
  public final static int YAP_CPP_DB_INTERFACE = yapJNI.YAP_CPP_DB_INTERFACE_get();
  public final static int YAPQ_HH = yapJNI.YAPQ_HH_get();
}
