/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class YAPCallback {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected YAPCallback(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YAPCallback obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yapJNI.delete_YAPCallback(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    yapJNI.YAPCallback_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    yapJNI.YAPCallback_change_ownership(this, swigCPtr, true);
  }

  public void run() {
    if (getClass() == YAPCallback.class) yapJNI.YAPCallback_run__SWIG_0(swigCPtr, this); else yapJNI.YAPCallback_runSwigExplicitYAPCallback__SWIG_0(swigCPtr, this);
  }

  public void run(String s) {
    if (getClass() == YAPCallback.class) yapJNI.YAPCallback_run__SWIG_1(swigCPtr, this, s); else yapJNI.YAPCallback_runSwigExplicitYAPCallback__SWIG_1(swigCPtr, this, s);
  }

  public YAPCallback() {
    this(yapJNI.new_YAPCallback(), true);
    yapJNI.YAPCallback_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
