/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class YAPEngine {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected YAPEngine(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YAPEngine obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yapJNI.delete_YAPEngine(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public YAPEngine(String savedState, String bootFile, long stackSize, long trailSize, long maxStackSize, long maxTrailSize, String libDir, String goal, String topLevel, boolean script, boolean fastBoot, YAPCallback callback) {
    this(yapJNI.new_YAPEngine__SWIG_0(savedState, bootFile, stackSize, trailSize, maxStackSize, maxTrailSize, libDir, goal, topLevel, script, fastBoot, YAPCallback.getCPtr(callback), callback), true);
  }

  public YAPEngine(String savedState, String bootFile, long stackSize, long trailSize, long maxStackSize, long maxTrailSize, String libDir, String goal, String topLevel, boolean script, boolean fastBoot) {
    this(yapJNI.new_YAPEngine__SWIG_1(savedState, bootFile, stackSize, trailSize, maxStackSize, maxTrailSize, libDir, goal, topLevel, script, fastBoot), true);
  }

  public YAPEngine(String savedState, String bootFile, long stackSize, long trailSize, long maxStackSize, long maxTrailSize, String libDir, String goal, String topLevel, boolean script) {
    this(yapJNI.new_YAPEngine__SWIG_2(savedState, bootFile, stackSize, trailSize, maxStackSize, maxTrailSize, libDir, goal, topLevel, script), true);
  }

  public YAPEngine(String savedState, String bootFile, long stackSize, long trailSize, long maxStackSize, long maxTrailSize, String libDir, String goal, String topLevel) {
    this(yapJNI.new_YAPEngine__SWIG_3(savedState, bootFile, stackSize, trailSize, maxStackSize, maxTrailSize, libDir, goal, topLevel), true);
  }

  public YAPEngine(String savedState, String bootFile, long stackSize, long trailSize, long maxStackSize, long maxTrailSize, String libDir, String goal) {
    this(yapJNI.new_YAPEngine__SWIG_4(savedState, bootFile, stackSize, trailSize, maxStackSize, maxTrailSize, libDir, goal), true);
  }

  public YAPEngine(String savedState, String bootFile, long stackSize, long trailSize, long maxStackSize, long maxTrailSize, String libDir) {
    this(yapJNI.new_YAPEngine__SWIG_5(savedState, bootFile, stackSize, trailSize, maxStackSize, maxTrailSize, libDir), true);
  }

  public YAPEngine(String savedState, String bootFile, long stackSize, long trailSize, long maxStackSize, long maxTrailSize) {
    this(yapJNI.new_YAPEngine__SWIG_6(savedState, bootFile, stackSize, trailSize, maxStackSize, maxTrailSize), true);
  }

  public YAPEngine(String savedState, String bootFile, long stackSize, long trailSize, long maxStackSize) {
    this(yapJNI.new_YAPEngine__SWIG_7(savedState, bootFile, stackSize, trailSize, maxStackSize), true);
  }

  public YAPEngine(String savedState, String bootFile, long stackSize, long trailSize) {
    this(yapJNI.new_YAPEngine__SWIG_8(savedState, bootFile, stackSize, trailSize), true);
  }

  public YAPEngine(String savedState, String bootFile, long stackSize) {
    this(yapJNI.new_YAPEngine__SWIG_9(savedState, bootFile, stackSize), true);
  }

  public YAPEngine(String savedState, String bootFile) {
    this(yapJNI.new_YAPEngine__SWIG_10(savedState, bootFile), true);
  }

  public YAPEngine(String savedState) {
    this(yapJNI.new_YAPEngine__SWIG_11(savedState), true);
  }

  public YAPEngine() {
    this(yapJNI.new_YAPEngine__SWIG_12(), true);
  }

  public YAPEngine(int argc, SWIGTYPE_p_p_char argv, YAPCallback callback) {
    this(yapJNI.new_YAPEngine__SWIG_13(argc, SWIGTYPE_p_p_char.getCPtr(argv), YAPCallback.getCPtr(callback), callback), true);
  }

  public YAPEngine(int argc, SWIGTYPE_p_p_char argv) {
    this(yapJNI.new_YAPEngine__SWIG_14(argc, SWIGTYPE_p_p_char.getCPtr(argv)), true);
  }

  public void delYAPCallback() {
    yapJNI.YAPEngine_delYAPCallback(swigCPtr, this);
  }

  public void setYAPCallback(YAPCallback cb) {
    yapJNI.YAPEngine_setYAPCallback(swigCPtr, this, YAPCallback.getCPtr(cb), cb);
  }

  public void run(String s) {
    yapJNI.YAPEngine_run(swigCPtr, this, s);
  }

  public YAPError hasError() {
    return new YAPError(yapJNI.YAPEngine_hasError(swigCPtr, this), true);
  }

  public YAPQuery query(String s) {
    long cPtr = yapJNI.YAPEngine_query(swigCPtr, this, s);
    return (cPtr == 0) ? null : new YAPQuery(cPtr, false);
  }

  public YAPModule currentModule() {
    return new YAPModule(yapJNI.YAPEngine_currentModule(swigCPtr, this), true);
  }

  public YAPTerm getTerm(SWIGTYPE_p_yhandle_t h) {
    return new YAPTerm(yapJNI.YAPEngine_getTerm(swigCPtr, this, SWIGTYPE_p_yhandle_t.getCPtr(h)), true);
  }

  public String currentDir() {
    return yapJNI.YAPEngine_currentDir(swigCPtr, this);
  }

  public String version() {
    return yapJNI.YAPEngine_version(swigCPtr, this);
  }

}
