/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class YAPError {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected YAPError(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YAPError obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yapJNI.delete_YAPError(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public YAPError() {
    this(yapJNI.new_YAPError__SWIG_0(), true);
  }

  public YAPError(int err) {
    this(yapJNI.new_YAPError__SWIG_1(err), true);
  }

  public int get() {
    return yapJNI.YAPError_get(swigCPtr, this);
  }

  public String text() {
    return yapJNI.YAPError_text(swigCPtr, this);
  }

}
