/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class YAPFunctor extends YAPProp {
  private transient long swigCPtr;

  protected YAPFunctor(long cPtr, boolean cMemoryOwn) {
    super(yapJNI.YAPFunctor_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YAPFunctor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yapJNI.delete_YAPFunctor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public YAPFunctor(YAPAtom at, long arity) {
    this(yapJNI.new_YAPFunctor__SWIG_0(YAPAtom.getCPtr(at), at, arity), true);
  }

  public YAPFunctor(String s, long arity, boolean isutf8) {
    this(yapJNI.new_YAPFunctor__SWIG_1(s, arity, isutf8), true);
  }

  public YAPFunctor(String s, long arity) {
    this(yapJNI.new_YAPFunctor__SWIG_2(s, arity), true);
  }

  public YAPFunctor(SWIGTYPE_p_wchar_t s, long arity) {
    this(yapJNI.new_YAPFunctor__SWIG_3(SWIGTYPE_p_wchar_t.getCPtr(s), arity), true);
  }

  public YAPAtom name() {
    return new YAPAtom(yapJNI.YAPFunctor_name(swigCPtr, this), true);
  }

  public long arity() {
    return yapJNI.YAPFunctor_arity(swigCPtr, this);
  }

}
