/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class YAPFLIP extends YAPPredicate {
  private transient long swigCPtr;

  protected YAPFLIP(long cPtr, boolean cMemoryOwn) {
    super(yapJNI.YAPFLIP_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YAPFLIP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yapJNI.delete_YAPFLIP(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public YAPFLIP(SWIGTYPE_p_CPredicate call, YAPAtom name, long arity, YAPModule module, SWIGTYPE_p_CPredicate retry, SWIGTYPE_p_CPredicate cut, long extra, boolean test) {
    this(yapJNI.new_YAPFLIP__SWIG_0(SWIGTYPE_p_CPredicate.getCPtr(call), YAPAtom.getCPtr(name), name, arity, YAPModule.getCPtr(module), module, SWIGTYPE_p_CPredicate.getCPtr(retry), SWIGTYPE_p_CPredicate.getCPtr(cut), extra, test), true);
  }

  public YAPFLIP(SWIGTYPE_p_CPredicate call, YAPAtom name, long arity, YAPModule module, SWIGTYPE_p_CPredicate retry, SWIGTYPE_p_CPredicate cut, long extra) {
    this(yapJNI.new_YAPFLIP__SWIG_1(SWIGTYPE_p_CPredicate.getCPtr(call), YAPAtom.getCPtr(name), name, arity, YAPModule.getCPtr(module), module, SWIGTYPE_p_CPredicate.getCPtr(retry), SWIGTYPE_p_CPredicate.getCPtr(cut), extra), true);
  }

  public YAPFLIP(SWIGTYPE_p_CPredicate call, YAPAtom name, long arity, YAPModule module, SWIGTYPE_p_CPredicate retry, SWIGTYPE_p_CPredicate cut) {
    this(yapJNI.new_YAPFLIP__SWIG_2(SWIGTYPE_p_CPredicate.getCPtr(call), YAPAtom.getCPtr(name), name, arity, YAPModule.getCPtr(module), module, SWIGTYPE_p_CPredicate.getCPtr(retry), SWIGTYPE_p_CPredicate.getCPtr(cut)), true);
  }

  public YAPFLIP(SWIGTYPE_p_CPredicate call, YAPAtom name, long arity, YAPModule module, SWIGTYPE_p_CPredicate retry) {
    this(yapJNI.new_YAPFLIP__SWIG_3(SWIGTYPE_p_CPredicate.getCPtr(call), YAPAtom.getCPtr(name), name, arity, YAPModule.getCPtr(module), module, SWIGTYPE_p_CPredicate.getCPtr(retry)), true);
  }

  public YAPFLIP(SWIGTYPE_p_CPredicate call, YAPAtom name, long arity, YAPModule module) {
    this(yapJNI.new_YAPFLIP__SWIG_4(SWIGTYPE_p_CPredicate.getCPtr(call), YAPAtom.getCPtr(name), name, arity, YAPModule.getCPtr(module), module), true);
  }

  public YAPFLIP(SWIGTYPE_p_CPredicate call, YAPAtom name, long arity) {
    this(yapJNI.new_YAPFLIP__SWIG_5(SWIGTYPE_p_CPredicate.getCPtr(call), YAPAtom.getCPtr(name), name, arity), true);
  }

  public YAPFLIP(String name, long arity, YAPModule module, boolean backtrackable) {
    this(yapJNI.new_YAPFLIP__SWIG_6(name, arity, YAPModule.getCPtr(module), module, backtrackable), true);
  }

  public YAPFLIP(String name, long arity, YAPModule module) {
    this(yapJNI.new_YAPFLIP__SWIG_7(name, arity, YAPModule.getCPtr(module), module), true);
  }

  public YAPFLIP(String name, long arity) {
    this(yapJNI.new_YAPFLIP__SWIG_8(name, arity), true);
  }

  public boolean addCall(SWIGTYPE_p_CPredicate call) {
    return yapJNI.YAPFLIP_addCall(swigCPtr, this, SWIGTYPE_p_CPredicate.getCPtr(call));
  }

  public boolean addRetry(SWIGTYPE_p_CPredicate call) {
    return yapJNI.YAPFLIP_addRetry(swigCPtr, this, SWIGTYPE_p_CPredicate.getCPtr(call));
  }

  public boolean addCut(SWIGTYPE_p_CPredicate call) {
    return yapJNI.YAPFLIP_addCut(swigCPtr, this, SWIGTYPE_p_CPredicate.getCPtr(call));
  }

}
