/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class YAPListTerm extends YAPTerm {
  private transient long swigCPtr;

  protected YAPListTerm(long cPtr, boolean cMemoryOwn) {
    super(yapJNI.YAPListTerm_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YAPListTerm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yapJNI.delete_YAPListTerm(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public YAPListTerm() {
    this(yapJNI.new_YAPListTerm__SWIG_0(), true);
  }

  public YAPListTerm(SWIGTYPE_p_Term t0) {
    this(yapJNI.new_YAPListTerm__SWIG_1(SWIGTYPE_p_Term.getCPtr(t0)), true);
  }

  public YAPListTerm(YAPTerm ts, long n) {
    this(yapJNI.new_YAPListTerm__SWIG_2(YAPTerm.getCPtr(ts), ts, n), true);
  }

  public long length() {
    return yapJNI.YAPListTerm_length(swigCPtr, this);
  }

  public YAPTerm car() {
    return new YAPTerm(yapJNI.YAPListTerm_car(swigCPtr, this), true);
  }

  public YAPListTerm cdr() {
    return new YAPListTerm(yapJNI.YAPListTerm_cdr(swigCPtr, this), true);
  }

  public YAPListTerm dup() {
    return new YAPListTerm(yapJNI.YAPListTerm_dup(swigCPtr, this), true);
  }

  public boolean nil() {
    return yapJNI.YAPListTerm_nil(swigCPtr, this);
  }

}
