/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class YAPNumberTerm extends YAPTerm {
  private transient long swigCPtr;

  protected YAPNumberTerm(long cPtr, boolean cMemoryOwn) {
    super(yapJNI.YAPNumberTerm_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YAPNumberTerm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yapJNI.delete_YAPNumberTerm(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public YAPNumberTerm() {
    this(yapJNI.new_YAPNumberTerm(), true);
  }

  public boolean isTagged() {
    return yapJNI.YAPNumberTerm_isTagged(swigCPtr, this);
  }

}
