/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class YAPPredicate extends YAPModuleProp {
  private transient long swigCPtr;

  protected YAPPredicate(long cPtr, boolean cMemoryOwn) {
    super(yapJNI.YAPPredicate_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YAPPredicate obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yapJNI.delete_YAPPredicate(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public YAPPredicate(YAPFunctor f) {
    this(yapJNI.new_YAPPredicate__SWIG_3(YAPFunctor.getCPtr(f), f), true);
  }

  public YAPPredicate(YAPFunctor f, YAPTerm mod) {
    this(yapJNI.new_YAPPredicate__SWIG_4(YAPFunctor.getCPtr(f), f, YAPTerm.getCPtr(mod), mod), true);
  }

  public YAPPredicate(YAPAtom at, YAPTerm mod) {
    this(yapJNI.new_YAPPredicate__SWIG_5(YAPAtom.getCPtr(at), at, YAPTerm.getCPtr(mod), mod), true);
  }

  public YAPPredicate(YAPAtom at) {
    this(yapJNI.new_YAPPredicate__SWIG_6(YAPAtom.getCPtr(at), at), true);
  }

  public YAPPredicate(YAPAtom at, long arity, YAPModule mod) {
    this(yapJNI.new_YAPPredicate__SWIG_7(YAPAtom.getCPtr(at), at, arity, YAPModule.getCPtr(mod), mod), true);
  }

  public YAPPredicate(YAPAtom at, long arity) {
    this(yapJNI.new_YAPPredicate__SWIG_8(YAPAtom.getCPtr(at), at, arity), true);
  }

  public YAPModule module() {
    return new YAPModule(yapJNI.YAPPredicate_module(swigCPtr, this), true);
  }

  public YAPAtom name() {
    return new YAPAtom(yapJNI.YAPPredicate_name(swigCPtr, this), true);
  }

  public long getArity() {
    return yapJNI.YAPPredicate_getArity(swigCPtr, this);
  }

}
