/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class YAPPairTerm extends YAPTerm {
  private transient long swigCPtr;

  protected YAPPairTerm(long cPtr, boolean cMemoryOwn) {
    super(yapJNI.YAPPairTerm_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YAPPairTerm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yapJNI.delete_YAPPairTerm(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public YAPPairTerm(YAPTerm hd, YAPTerm tl) {
    this(yapJNI.new_YAPPairTerm__SWIG_0(YAPTerm.getCPtr(hd), hd, YAPTerm.getCPtr(tl), tl), true);
  }

  public YAPPairTerm() {
    this(yapJNI.new_YAPPairTerm__SWIG_1(), true);
  }

  public YAPTerm getHead() {
    return new YAPTerm(yapJNI.YAPPairTerm_getHead(swigCPtr, this), true);
  }

  public YAPTerm getTail() {
    return new YAPTerm(yapJNI.YAPPairTerm_getTail(swigCPtr, this), true);
  }

}
