/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class YAPQuery extends YAPPredicate {
  private transient long swigCPtr;

  protected YAPQuery(long cPtr, boolean cMemoryOwn) {
    super(yapJNI.YAPQuery_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YAPQuery obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yapJNI.delete_YAPQuery(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public YAPQuery(YAPPredicate p, YAPTerm t) {
    this(yapJNI.new_YAPQuery__SWIG_0(YAPPredicate.getCPtr(p), p, YAPTerm.getCPtr(t), t), true);
  }

  public YAPQuery(YAPFunctor f, YAPTerm mod, YAPTerm t) {
    this(yapJNI.new_YAPQuery__SWIG_1(YAPFunctor.getCPtr(f), f, YAPTerm.getCPtr(mod), mod, YAPTerm.getCPtr(t), t), true);
  }

  public YAPQuery(YAPFunctor f, YAPTerm t) {
    this(yapJNI.new_YAPQuery__SWIG_2(YAPFunctor.getCPtr(f), f, YAPTerm.getCPtr(t), t), true);
  }

  public YAPQuery(String s) {
    this(yapJNI.new_YAPQuery__SWIG_3(s), true);
  }

  public YAPQuery(YAPAtom goal) {
    this(yapJNI.new_YAPQuery__SWIG_4(YAPAtom.getCPtr(goal), goal), true);
  }

  public void setFlag(int flag) {
    yapJNI.YAPQuery_setFlag(swigCPtr, this, flag);
  }

  public void resetFlag(int flag) {
    yapJNI.YAPQuery_resetFlag(swigCPtr, this, flag);
  }

  public boolean first() {
    return yapJNI.YAPQuery_first(swigCPtr, this);
  }

  public boolean next() {
    return yapJNI.YAPQuery_next(swigCPtr, this);
  }

  public boolean deterministic() {
    return yapJNI.YAPQuery_deterministic(swigCPtr, this);
  }

  public String text() {
    return yapJNI.YAPQuery_text(swigCPtr, this);
  }

  public void cut() {
    yapJNI.YAPQuery_cut(swigCPtr, this);
  }

  public void close() {
    yapJNI.YAPQuery_close(swigCPtr, this);
  }

  public YAPListTerm namedVars() {
    return new YAPListTerm(yapJNI.YAPQuery_namedVars(swigCPtr, this), true);
  }

  public YAPListTerm namedVarsCopy() {
    return new YAPListTerm(yapJNI.YAPQuery_namedVarsCopy(swigCPtr, this), true);
  }

  public YAPTerm getTerm(SWIGTYPE_p_yhandle_t t) {
    return new YAPTerm(yapJNI.YAPQuery_getTerm(swigCPtr, this, SWIGTYPE_p_yhandle_t.getCPtr(t)), true);
  }

  public boolean command() {
    return yapJNI.YAPQuery_command(swigCPtr, this);
  }

}
