/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class YAPStringTerm extends YAPTerm {
  private transient long swigCPtr;

  protected YAPStringTerm(long cPtr, boolean cMemoryOwn) {
    super(yapJNI.YAPStringTerm_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YAPStringTerm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yapJNI.delete_YAPStringTerm(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public YAPStringTerm(String s) {
    this(yapJNI.new_YAPStringTerm__SWIG_0(s), true);
  }

  public YAPStringTerm(String s, long len) {
    this(yapJNI.new_YAPStringTerm__SWIG_1(s, len), true);
  }

  public YAPStringTerm(SWIGTYPE_p_wchar_t s) {
    this(yapJNI.new_YAPStringTerm__SWIG_2(SWIGTYPE_p_wchar_t.getCPtr(s)), true);
  }

  public YAPStringTerm(SWIGTYPE_p_wchar_t s, long len) {
    this(yapJNI.new_YAPStringTerm__SWIG_3(SWIGTYPE_p_wchar_t.getCPtr(s), len), true);
  }

  public String getString() {
    return yapJNI.YAPStringTerm_getString(swigCPtr, this);
  }

}
