/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class YAPTerm {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected YAPTerm(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YAPTerm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yapJNI.delete_YAPTerm(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public YAPTerm(SWIGTYPE_p_Term tn) {
    this(yapJNI.new_YAPTerm__SWIG_0(SWIGTYPE_p_Term.getCPtr(tn)), true);
  }

  public YAPTerm() {
    this(yapJNI.new_YAPTerm__SWIG_1(), true);
  }

  public YAPTerm(SWIGTYPE_p_yhandle_t i) {
    this(yapJNI.new_YAPTerm__SWIG_2(SWIGTYPE_p_yhandle_t.getCPtr(i)), true);
  }

  public YAPTerm(SWIGTYPE_p_void ptr) {
    this(yapJNI.new_YAPTerm__SWIG_3(SWIGTYPE_p_void.getCPtr(ptr)), true);
  }

  public YAPTerm(String s) {
    this(yapJNI.new_YAPTerm__SWIG_4(s), true);
  }

  public SWIGTYPE_p_YAP_tag_t tag() {
    return new SWIGTYPE_p_YAP_tag_t(yapJNI.YAPTerm_tag(swigCPtr, this), true);
  }

  public YAPTerm deepCopy() {
    return new YAPTerm(yapJNI.YAPTerm_deepCopy(swigCPtr, this), true);
  }

  public int numberVars(int start, boolean skip_singletons) {
    return yapJNI.YAPTerm_numberVars__SWIG_0(swigCPtr, this, start, skip_singletons);
  }

  public int numberVars(int start) {
    return yapJNI.YAPTerm_numberVars__SWIG_1(swigCPtr, this, start);
  }

  public SWIGTYPE_p_Term term() {
    return new SWIGTYPE_p_Term(yapJNI.YAPTerm_term(swigCPtr, this), true);
  }

  public boolean exactlyEqual(YAPTerm t1) {
    return yapJNI.YAPTerm_exactlyEqual(swigCPtr, this, YAPTerm.getCPtr(t1), t1);
  }

  public boolean unify(YAPTerm t1) {
    return yapJNI.YAPTerm_unify(swigCPtr, this, YAPTerm.getCPtr(t1), t1);
  }

  public boolean unifiable(YAPTerm t1) {
    return yapJNI.YAPTerm_unifiable(swigCPtr, this, YAPTerm.getCPtr(t1), t1);
  }

  public boolean variant(YAPTerm t1) {
    return yapJNI.YAPTerm_variant(swigCPtr, this, YAPTerm.getCPtr(t1), t1);
  }

  public int hashTerm(long sz, long depth, boolean variant) {
    return yapJNI.YAPTerm_hashTerm(swigCPtr, this, sz, depth, variant);
  }

  public boolean isVar() {
    return yapJNI.YAPTerm_isVar(swigCPtr, this);
  }

  public boolean isAtom() {
    return yapJNI.YAPTerm_isAtom(swigCPtr, this);
  }

  public boolean isInteger() {
    return yapJNI.YAPTerm_isInteger(swigCPtr, this);
  }

  public boolean isFloat() {
    return yapJNI.YAPTerm_isFloat(swigCPtr, this);
  }

  public boolean isString() {
    return yapJNI.YAPTerm_isString(swigCPtr, this);
  }

  public boolean isCompound() {
    return yapJNI.YAPTerm_isCompound(swigCPtr, this);
  }

  public boolean isAppl() {
    return yapJNI.YAPTerm_isAppl(swigCPtr, this);
  }

  public boolean isPair() {
    return yapJNI.YAPTerm_isPair(swigCPtr, this);
  }

  public boolean isGround() {
    return yapJNI.YAPTerm_isGround(swigCPtr, this);
  }

  public boolean isList() {
    return yapJNI.YAPTerm_isList(swigCPtr, this);
  }

  public YAPTerm getArg(long i) {
    return new YAPTerm(yapJNI.YAPTerm_getArg(swigCPtr, this, i), true);
  }

  public long arity() {
    return yapJNI.YAPTerm_arity(swigCPtr, this);
  }

  public String text() {
    return yapJNI.YAPTerm_text(swigCPtr, this);
  }

  public SWIGTYPE_p_yhandle_t handle() {
    return new SWIGTYPE_p_yhandle_t(yapJNI.YAPTerm_handle(swigCPtr, this), true);
  }

}
