/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pt.up.yap.lib;

public class YAPVarTerm extends YAPTerm {
  private transient long swigCPtr;

  protected YAPVarTerm(long cPtr, boolean cMemoryOwn) {
    super(yapJNI.YAPVarTerm_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(YAPVarTerm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        yapJNI.delete_YAPVarTerm(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public YAPVarTerm() {
    this(yapJNI.new_YAPVarTerm(), true);
  }

  public SWIGTYPE_p_CELL getVar() {
    long cPtr = yapJNI.YAPVarTerm_getVar(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_CELL(cPtr, false);
  }

  public boolean unbound() {
    return yapJNI.YAPVarTerm_unbound(swigCPtr, this);
  }

  public boolean isVar() {
    return yapJNI.YAPVarTerm_isVar(swigCPtr, this);
  }

  public boolean isAtom() {
    return yapJNI.YAPVarTerm_isAtom(swigCPtr, this);
  }

  public boolean isInteger() {
    return yapJNI.YAPVarTerm_isInteger(swigCPtr, this);
  }

  public boolean isFloat() {
    return yapJNI.YAPVarTerm_isFloat(swigCPtr, this);
  }

  public boolean isString() {
    return yapJNI.YAPVarTerm_isString(swigCPtr, this);
  }

  public boolean isCompound() {
    return yapJNI.YAPVarTerm_isCompound(swigCPtr, this);
  }

  public boolean isAppl() {
    return yapJNI.YAPVarTerm_isAppl(swigCPtr, this);
  }

  public boolean isPair() {
    return yapJNI.YAPVarTerm_isPair(swigCPtr, this);
  }

  public boolean isGround() {
    return yapJNI.YAPVarTerm_isGround(swigCPtr, this);
  }

  public boolean isList() {
    return yapJNI.YAPVarTerm_isList(swigCPtr, this);
  }

}
